//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adres
    {
        public int id_adresu { get; set; }
        public int id_klienta { get; set; }
        public int id_kodu_pocztowego { get; set; }
        public int id_miejscowosci { get; set; }
        public int id_wojewodztwa { get; set; }
        public string ulica { get; set; }
        public string numer_domu { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual Kod_Pocztowy Kod_Pocztowy { get; set; }
        public virtual Miejscowosc Miejscowosc { get; set; }
        public virtual Wojewodztwo Wojewodztwo { get; set; }
    }
}
