//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Miejsca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Miejsca()
        {
            this.Pracownicy = new HashSet<Pracownicy>();
            this.Wypozyczenia = new HashSet<Wypozyczenia>();
            this.Wypozyczenia1 = new HashSet<Wypozyczenia>();
        }
    
        public int id_miejsca { get; set; }
        [Required(ErrorMessage = "Proszê podaæ ulicê.")]
        public string ulica { get; set; }
        [Required(ErrorMessage = "Proszê podaæ numer lokalu.")]
        [RegularExpression(@"^(\d{1,4})(\s{0,1})([a-zA-Z]{0,1})$", ErrorMessage = "Proszê podaæ poprawny numer lokalu.")]
        public string numer { get; set; }
        [Required(ErrorMessage = "Proszê podaæ kod pocztowy.")]
        [RegularExpression(@"^([0-9]{2})[-]([0-9]{3})$", ErrorMessage = "Kod pocztowy musi byæ w formacie: 00-000")]
        public string kod_pocztowy { get; set; }
        [Required(ErrorMessage = "Proszê podaæ miejscowoœæ, w której znajduje siê firma.")]
        public string miejscowosc { get; set; }
        [Phone]
        [Required(ErrorMessage = "Proszê podaæ numer telefonu.")]
        [RegularExpression(@"^([0-9]{3})[ \s]\ ?([0-9]{3})[ \s]\ ?([0-9]{3})$",
                ErrorMessage = "Numer musi byæ w formacie: 123 123 123")]
        public string numer_tel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pracownicy> Pracownicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wypozyczenia> Wypozyczenia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wypozyczenia> Wypozyczenia1 { get; set; }
    }
}
