//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pracownicy()
        {
            this.Wypozyczenia = new HashSet<Wypozyczenia>();
        }
    
        public int id_pracownika { get; set; }
        public int id_miejsca_pracy { get; set; }
        public int id_konta_pr { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public System.DateTime data_zatrudnienia { get; set; }
        public string stanowisko { get; set; }
    
        public virtual Konta Konta { get; set; }
        public virtual Miejsca Miejsca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wypozyczenia> Wypozyczenia { get; set; }
    }
}
