//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Samochody
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Samochody()
        {
            this.Wypozyczenia = new HashSet<Wypozyczenia>();
        }
    
        public int id_samochodu { get; set; }
        public int id_wyposazenia { get; set; }
        public int id_marki { get; set; }
        public int id_modelu { get; set; }
        public int id_typu { get; set; }
        public int id_koloru { get; set; }
        public int id_paliwa { get; set; }
        public string rok_prod { get; set; }
        public string poj_silnika { get; set; }
        public decimal przebieg { get; set; }
    
        public virtual Kolor Kolor { get; set; }
        public virtual Marka Marka { get; set; }
        public virtual Model Model { get; set; }
        public virtual Paliwo Paliwo { get; set; }
        public virtual Wyposazenie Wyposazenie { get; set; }
        public virtual Typ Typ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wypozyczenia> Wypozyczenia { get; set; }
    }
}
