//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wypozyczenia
    {
        public int id_wypozyczenia { get; set; }
        public int id_samochodu { get; set; }
        public int id_klienta { get; set; }
        public int id_pracownika { get; set; }
        public int id_miejsca_wyp { get; set; }
        public Nullable<int> id_miejsca_odd { get; set; }
        public System.DateTime data_wyp { get; set; }
        public Nullable<System.DateTime> data_odd { get; set; }
        public decimal koszt { get; set; }
        public Nullable<decimal> kaucja { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual Miejsca Miejsca { get; set; }
        public virtual Miejsca Miejsca1 { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Samochody Samochody { get; set; }
    }
}
